apiVersion: v1
kind: DeploymentConfig
metadata:
  name: product-catalog
spec:
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - product-catalog
        from:
          kind: ImageStreamTag
          namespace: product
          name: 'product-catalog:latest'
  replicas: 1
  template:
    metadata:
      labels:
        app: product-catalog      
    spec:
      initContainers:
      - name: pem-to-truststore
        image: registry.access.redhat.com/redhat-sso-7/sso71-openshift:1.1-16
        env:
          - name: ca_bundle
            value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          - name: truststore_jks
            value: /var/run/secrets/java.io/keystores/truststore.jks
          - name: password
            value: changeit    
        command: ['/bin/bash']
        args: ['-c', "csplit -z -f crt- $ca_bundle '/-----BEGIN CERTIFICATE-----/' '{*}' && for file in crt-*; do keytool -import -noprompt -keystore $truststore_jks -file $file -storepass changeit -alias service-$file; done"]
        volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores 
#      - name: istio-init
#        args:
#        - -p
#        - "15001"
#        - -u
#        - "1337"
#        image: docker.io/istio/proxy_init:0.4.0
#        imagePullPolicy: IfNotPresent        
#        securityContext:
#          capabilities:
#            add:
#            - NET_ADMIN
#          privileged: true                 
      containers:
#      - args:
#        - proxy
#        - sidecar
#        - -v
#        - "2"
#        - --configPath
#        - /etc/istio/proxy
#        - --binaryPath
#        - /usr/local/bin/envoy
#        - --serviceCluster
#        - product-catalog
#        - --drainDuration
#        - 45s
#        - --parentShutdownDuration
#        - 1m0s
#        - --discoveryAddress
#        - istio-pilot.istio-system:15003
#        - --discoveryRefreshDelay
#        - 1s
#        - --zipkinAddress
#        - zipkin.istio-system:9411
#        - --connectTimeout
#        - 10s
#        - --statsdUdpAddress
#        - istio-mixer.istio-system:9125
#        - --proxyAdminPort
#        - "15000"
#        - --controlPlaneAuthPolicy
#        - NONE
#        env:
#        - name: POD_NAME
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.name
#        - name: POD_NAMESPACE
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.namespace
#        - name: INSTANCE_IP
#          valueFrom:
#            fieldRef:
#              fieldPath: status.podIP
#        image: docker.io/istio/proxy:0.4.0
#        imagePullPolicy: IfNotPresent
#        name: istio-proxy
#        resources: {}
#        securityContext:
#          privileged: false
#          readOnlyRootFilesystem: true
#          runAsUser: 1337
#        volumeMounts:
#        - mountPath: /etc/istio/proxy
#          name: istio-envoy
#        - mountPath: /etc/certs/
#          name: istio-certs
#          readOnly: true
      - name: product-catalog
        image: "product/product-catalog:latest"
        imagePullPolicy: Always
        env:     
        - name: JAVA_OPTIONS
          value: -Dspring.profiles.active=openshift -Djavax.net.ssl.trustStore=/var/run/secrets/java.io/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit                      
        volumeMounts:
        - name: keystore-volume
          mountPath: /var/run/secrets/java.io/keystores            
      volumes:
      - name: keystore-volume
        emptyDir: {}         
#      - emptyDir:
#          medium: Memory
#          sizeLimit: "0"
#        name: istio-envoy
#      - name: istio-certs
#        secret:
#          optional: true
#          secretName: istio.default             
